version: "3.8"

services:

  db:
    image: postgres:14.1-alpine
    container_name: luxonis-test-dtb
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: test
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/create_tables.sql

  api-server:
    build:
      context: .
    depends_on:
      - db
    container_name: luxonis-test-app
    image: luxonis-test-app
    restart: unless-stopped
    ports:
      - 3000:3000
    environment:
      NODE_ENV: production
      PORT: 3000
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_NAME: test
    links:
      - db

volumes:
  db:
    driver: local
